In [154]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

# Load the dataset

In [155]:
weather_data = pd.read_csv(r"D:\University\3-2\3211\Lab_5_Assignment\1901_2023_BD_weather.csv")
weather_data.head()

   Year  Month  Temperature     Rain
0  1901      1         16.98   18.54
1  1901      2         19.90   16.25
2  1901      3         24.32   70.80
3  1901      4         28.18   66.16
4  1901      5         27.89  267.22

# Inspect data

In [156]:
print(weather_data.info())
print(weather_data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          1474 non-null   int64
 1   Month         1474 non-null   int64
 2   Temperature   1474 non-null   float64
 3   Rain          1474 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 46.2 KB
None
   Year  Month  Temperature     Rain
0  1901      1         16.98   18.54
1  1901      2         19.90   16.25
2  1901      3         24.32   70.80
3  1901      4         28.18   66.16
4  1901      5         27.89  267.22

In [157]:
weather_data.head(10)

   Year  Month  Temperature     Rain
0  1901      1         16.98   18.54
1  1901      2         19.90   16.25
2  1901      3         24.32   70.80
3  1901      4         28.18   66.16
4  1901      5         27.89  267.22
5  1901      6         28.89  341.04
6  1901      7         28.33  540.91
7  1901      8         27.92  493.21
8  1901      9         27.61  291.55
9  1901     10         27.09  199.17

# Define Features and Targets

In [158]:
df1 = weather_data[(weather_data['Month'] == 11) | (weather_data['Month'] == 12)]
X = df1.drop(['Temperature ', 'Rain'], axis=1)
y_temp = df1['Temperature ']
y_rain = df1['Rain']

In [159]:
df1.head(10)

    Year  Month  Temperature     Rain
10  1901     11         22.17  126.29
11  1901     12         18.56    1.69
22  1902     11         21.99    4.48
23  1902     12         18.25    6.52
34  1903     11         22.43   53.80
35  1903     12         18.37    0.01
46  1904     11         22.15   32.95
47  1904     12         18.78    1.98
58  1905     11         22.69    4.92
59  1905     12         18.67    7.62

In [160]:
X.head(10)

    Year  Month
10  1901     11
11  1901     12
22  1902     11
23  1902     12
34  1903     11
35  1903     12
46  1904     11
47  1904     12
58  1905     11
59  1905     12

In [161]:
y_temp.head(10)

10    22.17
11    18.56
22    21.99
23    18.25
34    22.43
35    18.37
46    22.15
47    18.78
58    22.69
59    18.67
Name: Temperature , dtype: float64

In [162]:
y_rain.head(10)

10    126.29
11      1.69
22      4.48
23      6.52
34     53.80
35      0.01
46     32.95
47      1.98
58      4.92
59      7.62
Name: Rain, dtype: float64

# Split the Data

In [163]:
X_train, X_test, y_temp_train, y_temp_test, y_rain_train, y_rain_test = train_test_split(X, y_temp, y_rain, test_size=0.2, random_state=1, shuffle=False)

In [164]:
X_train.head(10)

    Year  Month
10  1901     11
11  1901     12
22  1902     11
23  1902     12
34  1903     11
35  1903     12
46  1904     11
47  1904     12
58  1905     11
59  1905     12

In [165]:
X_test.head(10)

      Year  Month
1175  1998     12
1186  1999     11
1187  1999     12
1198  2000     11
1199  2000     12
1210  2001     11
1211  2001     12
1222  2002     11
1223  2002     12
1234  2003     11

# Model Training for Temperature and Rainfall

In [166]:
temp_model = LinearRegression()
rain_model = LinearRegression()

temp_model.fit(X_train, y_temp_train)
rain_model.fit(X_train, y_rain_train)

LinearRegression()

# Model Evaluation on Test Data

In [167]:
y_temp_pred = temp_model.predict(X_test)
y_rain_pred = rain_model.predict(X_test)

# Forecasting for November and December 2024

In [168]:

future_dates = pd.DataFrame({'Year': [2024, 2024],'Month': [11, 12]})
nov_dec_temp_pred = temp_model.predict(future_dates)
nov_dec_rain_pred = rain_model.predict(future_dates)

# Display predictions

In [169]:
nov_dec_temp_pred = temp_model.predict(future_dates)
nov_dec_rain_pred = rain_model.predict(future_dates)

print("Predictions for November and December 2024:\n")

print(f"Temperature in November is {nov_dec_temp_pred[0]:.8f} °C")
print(f"Temperature in December is {nov_dec_temp_pred[1]:.8f} °C\n")

print(f"Rainfall in November is {nov_dec_rain_pred[0]:.8f} mm")
print(f"Rainfall in December is {nov_dec_rain_pred[1]:.8f} mm")

Predictions for November and December 2024:

Temperature in November is 23.77263973 °C
Temperature in December is 19.99369564 °C

Rainfall in November is 36.99640567 mm
Rainfall in December is 9.20959685 mm

# Performance metrics for temperature and rainfall

In [170]:
temp_mae = mean_absolute_error(y_temp_test, y_temp_pred)
temp_rmse = np.sqrt(mean_squared_error(y_temp_test, y_temp_pred))

In [171]:
rain_mae = mean_absolute_error(y_rain_test, y_rain_pred)
rain_rmse = np.sqrt(mean_squared_error(y_rain_test, y_rain_pred))

In [ ]:
print(f"Temperature_MAE: {temp_mae}, Temperature RMSE: {temp_rmse}")
print(f"Rainfall_MAE: {rain_mae}, Rainfall RMSE: {rain_rmse}")

Temperature MAE: 0.7195567852543596, Temperature RMSE: 0.8969508042331947
Rainfall MAE: 18.52040379685837, Rainfall RMSE: 27.427074057091623