# Import necessary libraries

In [68]:
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Create a synthetic dataset for demonstration

In [69]:
x,y = make_classification(n_samples=20000, n_features=10, n_classes=2, random_state=42)

# Split the dataset into training and testing sets(80-20 split)

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=42)

In [71]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9
0,-0.847375,1.184900,-0.655617,-1.097094,1.355763,-1.299929,1.461357,-1.933971,1.101042,0.226124
1,-0.208750,-0.240534,-0.921611,1.237373,1.257983,-0.765472,0.514975,-0.437249,-0.387892,0.221900
2,0.672944,-0.685776,-0.911954,-2.158696,0.222110,1.008237,-0.230126,1.537987,-0.910077,-0.759541
3,-0.929259,1.432996,0.792620,-0.549814,-0.370799,-1.065767,0.010678,-2.152517,1.740059,0.806284
4,-0.229712,-0.343220,-0.969324,0.779586,0.476038,1.341656,-0.329360,-0.673359,2.806373,0.298234
...,...,...,...,...,...,...,...,...,...,...
13995,0.611581,-1.529631,0.323622,0.308535,0.021382,0.781117,1.238310,1.409641,-1.027218,-0.142864
13996,-0.595094,1.358224,-0.935716,-1.449962,-0.581774,-1.211333,-2.133204,-1.331927,0.331456,0.271343
13997,-1.062421,-0.082219,-0.282279,-0.541995,-0.074946,-2.177724,0.527196,-2.376555,0.569346,0.295964
13998,-0.103967,0.587999,2.009250,-1.031911,-0.751471,1.189728,0.548788,-0.356024,2.132497,-0.748856
13999,0.211543,-0.232992,1.205574,-1.283044,0.973421,0.719569,-0.375940,0.448039,0.309965,-0.369104

In [72]:
pd.DataFrame(x_test)

,0,1,2,3,4,5,6,7,8,9
0,0.158595,-0.488326,-0.417768,-0.556549,-1.076607,-0.550887,0.397947,0.431856,-1.381792,2.498049
1,0.062905,0.239388,-1.603936,-1.136106,-1.746414,1.030975,-0.175919,0.061331,1.301672,0.473795
2,-0.497828,-0.760042,-1.032371,-0.297587,1.194801,0.406107,-0.741072,-1.239145,2.378656,-0.306717
3,0.783616,-2.821496,0.431549,-2.115926,1.233650,1.089360,0.321560,1.798376,-1.185127,1.276500
4,-0.304351,-0.116932,0.196545,-0.332119,1.076904,-0.822201,1.211230,-0.663354,-0.130540,-1.570369
...,...,...,...,...,...,...,...,...,...,...
5995,-0.118456,-1.880368,0.470230,0.039208,1.701805,0.938151,1.758868,-0.368906,1.811787,0.039517
5996,-0.771162,0.318519,-0.244171,0.409073,-2.073193,-0.733263,-0.245163,-1.799611,1.667833,-0.314942
5997,0.597712,-0.053098,-0.374282,-0.867092,0.503268,0.081968,1.156007,1.437643,-2.012730,0.323490
5998,-0.728157,0.255765,-0.605814,0.696835,-0.307754,-0.677812,0.550023,-1.700534,1.596379,-0.615559
5999,-0.438241,0.224812,-1.596087,-0.297194,0.284265,-1.490019,-0.287946,-0.928237,-0.641145,-1.147590

In [74]:
x_train.shape

(14000, 10)

In [76]:
y_train.shape

(14000,)

In [77]:
x_test.shape

(6000, 10)

In [78]:
y_test.shape

(6000,)